

SET TERMOUT ON
SET FEEDBACK ON
SET LINESIZE 200
SET TAB OFF
SET TRIM ON
SET TRIMSPOOL ON
SET SERVEROUT ON size 30000
SET LONG 100000
SET PAGESIZE 200
SET FEEDBACK OFF
ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT='DD-MON-YYYY HH24:MI:SS.FF';
SET FEEDBACK ON


col machine for a30
col username for a10
set pages 200 lines 200
set numwidth 6

